[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = { path = "macros" }
itertools = "0.10.5"
regex = "1.7.0"
serde_json = "1.0.89"
anyhow = "1.0.66"
